-- Create patients table
CREATE TABLE IF NOT EXISTS patients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama TEXT NOT NULL,
  nik TEXT NOT NULL UNIQUE,
  "noBpjs" TEXT,
  "tglLahir" DATE NOT NULL,
  umur INTEGER,
  "jenisKelamin" TEXT NOT NULL,
  alamat TEXT NOT NULL,
  "noHp" TEXT NOT NULL,
  "namaKontak" TEXT NOT NULL,
  "hubKontak" TEXT NOT NULL,
  "noHpKontak" TEXT,
  "statusPasien" TEXT NOT NULL,
  "tglDaftar" DATE NOT NULL DEFAULT CURRENT_DATE,
  
  -- Nurse triage fields
  keluhan TEXT,
  "beratBadan" NUMERIC,
  "tinggiBadan" NUMERIC,
  imt NUMERIC,
  "lingkarKepala" NUMERIC,
  "lingkarLengan" NUMERIC,
  "golDarah" TEXT,
  rr INTEGER,
  spo2 INTEGER,
  "suplemenO2" TEXT,
  suhu NUMERIC,
  sistolik INTEGER,
  diastolik INTEGER,
  nadi INTEGER,
  avpu TEXT,
  "meowsScore" INTEGER DEFAULT 0,
  "triageRisk" TEXT,
  "tglTriage" TEXT,
  
  -- Doctor diagnosis fields
  diagnosa TEXT,
  "rencanaTerapi" TEXT,
  disposisi TEXT,
  "statusDiagnosis" TEXT DEFAULT 'Belum Diperiksa'
);

-- Seed initial mock data
INSERT INTO patients (
  nama, nik, "noBpjs", "tglLahir", umur, "jenisKelamin", alamat, "noHp", 
  "namaKontak", "hubKontak", "noHpKontak", "statusPasien", "tglDaftar",
  keluhan, "beratBadan", "tinggiBadan", imt, "lingkarKepala", "lingkarLengan", 
  "golDarah", rr, spo2, "suplemenO2", suhu, sistolik, diastolik, nadi, avpu, 
  "meowsScore", "triageRisk", "tglTriage", diagnosa, "rencanaTerapi", disposisi, "statusDiagnosis"
) VALUES (
  'Siti Rahayu', '3201234567890001', '0001234567890', '1985-03-12', 39, 'Perempuan', 'Jl. Merdeka No. 10, Bekasi', '08123456789',
  'Budi Rahayu', 'Suami', '08122222222', 'BPJS', '2025-06-20',
  'Nyeri dada sebelah kiri menjalar ke lengan kiri sejak 2 jam lalu', 58, 155, 24.1, NULL, 26,
  'O', 16, 98, 'Tidak', 36.6, 120, 80, 78, 'Alert',
  0, 'Low', '2025-06-20 22:45', '', '', '', 'Belum Diperiksa'
),
(
  'Ahmad Fauzi', '3201234567890002', '', '1992-07-25', 32, 'Laki-laki', 'Jl. Sudirman No. 5, Jakarta', '08234567890',
  'Dewi Fauzi', 'Istri', '08233333333', 'Umum', '2025-06-21',
  'Sesak napas disertai demam tinggi sejak kemarin sore', 75, 172, 25.4, NULL, 29,
  'A+', 24, 93, 'Ya', 38.5, 98, 65, 112, 'Alert',
  8, 'High', '2025-06-21 14:12', 'Pneumonia Lobaris Dextra', 'Oksigenasi kanula nasal 3 lpm, Infus NaCl 0.9% 20 tpm, IV Ceftriaxone 2x1g, Nebulizer Ventolin per 8 jam.', 'Rawat Inap', 'Sudah Diperiksa'
),
(
  'Rizky Aditya (Bayi)', '3201234567890004', '0001234567895', '2024-11-10', 0, 'Laki-laki', 'Jl. Anggrek No. 12, Bekasi', '08456789012',
  'Siska Aditya', 'Ibu', NULL, 'BPJS', '2025-06-22',
  'Demam naik turun dan rewel sejak 1 hari yang lalu', 8.5, 72, 16.4, 44, 13.5,
  'B', 28, 97, 'Tidak', 37.1, 85, 55, 125, 'Alert',
  1, 'Low', '2025-06-22 09:30', '', '', '', 'Belum Diperiksa'
) ON CONFLICT (nik) DO NOTHING;
